# Generated by Django 2.0.1 on 2018-01-13 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
